# Generated by Django 4.0.6 on 2022-08-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_message_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default=1, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
