# Generated by Django 4.0.6 on 2022-08-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_message_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='email1',
        ),
        migrations.AddField(
            model_name='message',
            name='email2',
            field=models.EmailField(default=1, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
