# Generated by Django 4.0.6 on 2022-08-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_email_message_email1_message_email2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email2',
            field=models.EmailField(max_length=50, verbose_name='Email_2'),
        ),
    ]
