# Generated by Django 4.0.6 on 2022-08-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_message_email2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email2',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email_2'),
        ),
    ]
